In [1]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import euclidean_distances

In [2]:
corpus = ["ordinary, soap, weird",
        "ordinary, loop, soap",
        "food, pantry, car",
        "ticket,pantry,passenger",
         "ordinary,soap,weird",
         "ordinary,towel,normal",
         "food,pantry,car",
         "ordinary, loop1, soap, random"]

In [3]:
db_add=input("Enter a new price list(PL) entry: ")
corpus.append(str(db_add))

Enter a new price list(PL) entry: ordinary,soap,weird


In [4]:
corpus

['ordinary, soap, weird',
 'ordinary, loop, soap',
 'food, pantry, car',
 'ticket,pantry,passenger',
 'ordinary,soap,weird',
 'ordinary,towel,normal',
 'food,pantry,car',
 'ordinary, loop1, soap, random',
 'ordinary,soap,weird']

In [5]:
vectorizer=CountVectorizer()
features=vectorizer.fit_transform(corpus).todense()
print(features)

[[0 0 0 0 0 1 0 0 0 1 0 0 1]
 [0 0 1 0 0 1 0 0 0 1 0 0 0]
 [1 1 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 1 0 0]
 [0 0 0 0 0 1 0 0 0 1 0 0 1]
 [0 0 0 0 1 1 0 0 0 0 0 1 0]
 [1 1 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 1 1 0 0 0]
 [0 0 0 0 0 1 0 0 0 1 0 0 1]]


In [6]:
# tags = text.split(',')
# number = len(tags)

In [7]:
vectorizer.vocabulary_

{'ordinary': 5,
 'soap': 9,
 'weird': 12,
 'loop': 2,
 'food': 1,
 'pantry': 6,
 'car': 0,
 'ticket': 10,
 'passenger': 7,
 'towel': 11,
 'normal': 4,
 'loop1': 3,
 'random': 8}

In [8]:
for f in features:
    print(euclidean_distances(features[0],f))

[[0.]]
[[1.41421356]]
[[2.44948974]]
[[2.44948974]]
[[0.]]
[[2.]]
[[2.44948974]]
[[1.73205081]]
[[0.]]


In [9]:
# for f in features:
#     sum1=0
#     f.tolist()
#     print(f[0][0])
#     for s in f:
#         sum1=sum1+s
#     #print(sum1)
    #print(abs(f-features[0]))


In [10]:
type(features)

numpy.matrix

In [11]:
featurelist=features.tolist()
featurelist

[[0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1],
 [0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
 [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1],
 [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0],
 [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1]]

In [12]:
import numpy as np
featurelist[0]=np.array(featurelist[0])
featurelist[1]=np.array(featurelist[1])
sum(abs(featurelist[0]-featurelist[1]))

2

In [18]:
for i in range(len(featurelist)):
    featurelist[i]=np.array(featurelist[i])

    

In [25]:
sum(featurelist)

array([2, 2, 1, 1, 1, 6, 3, 1, 1, 5, 1, 1, 3])

In [16]:
# #for feature in features:
# sumq=0
# for f in featurelist:
#     sumq+=f
#     print(abs(feature-features[0].tolist()))
#     print(sumq)
    

9